# Generated by Django 5.0.1 on 2025-06-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=200)),
                ('domains', models.TextField()),
                ('training_from', models.DateField()),
                ('training_to', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Cash', 'Cash')], max_length=10)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
