# Generated by Django 5.0.1 on 2025-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='date',
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='domains',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
    ]
