# Generated by Django 5.0.1 on 2025-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_remove_internshipapplication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
