# Generated by Django 5.0.1 on 2025-06-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_internshipapplication_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='batch_from',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='batch_to',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='father_name',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='mother_name',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
