# Generated by Django 5.0.1 on 2025-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_internshipapplication_batch_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='fees',
        ),
    ]
