# Generated by Django 5.0.1 on 2025-08-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_remove_internshipapplication_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='training_to',
        ),
    ]
