# Generated by Django 5.0.1 on 2025-08-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_remove_internshipapplication_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='father_mobile',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='mother_mobile',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='mother_name',
        ),
    ]
