# Generated by Django 5.0.1 on 2025-09-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_remove_internshipapplication_father_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='training_from',
        ),
    ]
