# Generated by Django 5.0.1 on 2025-09-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_remove_internshipapplication_training_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
