# Generated by Django 5.0.1 on 2025-09-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_internshipapplication_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='photo',
        ),
    ]
